name: "Polaris Scan Action"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        # We must fetch at least the immediate parents so that if this is
        # a pull request then we can checkout the head.
        fetch-depth: 2

    # If this run was triggered by a pull request event, then checkout
    # the head of the pull request instead of the merge commit.
    - run: git checkout HEAD^2
      if: ${{ github.event_name == 'pull_request' }}
      
    - name: Static Analysis with Polaris Action
      uses: devsecops-test/polaris-action@c362842
      with:
        polarisServerUrl: ${{secrets.POLARIS_SERVER_URL_CSPROD}}
        polarisAccessToken: ${{secrets.POLARIS_ACCESS_TOKEN_CSPROD}}
        polarisProjectName: polaris-action-sample
    
    - name: Incremental Static Analysis with Polaris Action for a single commit
      if: ${{github.event_name == 'push1'}}
      uses: devsecops-test/polaris-action@c362842
      with:
        polarisServerUrl: ${{secrets.POLARIS_SERVER_URL}}
        polarisAccessToken: ${{secrets.POLARIS_ACCESS_TOKEN}}
        polarisProjectName: polaris-action-sample
        polarisAdditionalArgs: --coverity-ignore-capture-failure --incremental polaris-files-to-scan.txt | tee polaris-output.txt
        githubUrl: https://api.github.com/repos/${{github.repository}}/commits/${{github.sha}}
        #githubCreds: "${{secrets.GITHUB_USERNAME}}:${{secrets.GITHUB_TOKEN}}"     #Needed only if repository is private
    
    - name: Incremental Static Analysis with Polaris Action for Pull Request
      if: ${{github.event_name == 'pull_request1'}}
      uses: devsecops-test/polaris-action@c362842
      with:
        polarisServerUrl: ${{secrets.POLARIS_SERVER_URL}}
        polarisAccessToken: ${{secrets.POLARIS_ACCESS_TOKEN}}
        polarisProjectName: polaris-action-sample
        polarisAdditionalArgs: --coverity-ignore-capture-failure --incremental polaris-files-to-scan.txt | tee polaris-output.txt
        githubUrl: https://api.github.com/repos/${{github.repository}}/pulls/$(jq --raw-output .pull_request.number ${{github.event_path}})/files
        #githubCreds: "${{secrets.GITHUB_USERNAME}}:${{secrets.GITHUB_TOKEN}}"     #Needed only if repository is private
    
    #- name: Upload Release Asset
    #  id: upload-release-asset 
    #  uses: actions/upload-release-asset@v1.0.2
    #  env:
    #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #  with:
    #    upload_url: 'https://uploads.github.com/repos/devsecops-test/polaris-action-sample/releases/35071535/assets{?name,label}'
    #    asset_path: polaris-scan-results.sarif.json
    #    asset_name: polaris-action.sarif.json
    #    asset_content_type: application/json
    
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v1
      with:
        # Path to SARIF file relative to the root of the repository
        sarif_file: polaris-scan-results.sarif.json
